set(CTEST_PROJECT_NAME       "XCFun")
set(CTEST_NIGHTLY_START_TIME "03:00:00 CEST")
set(CTEST_DROP_METHOD        "http")
set(CTEST_DROP_SITE          "repo.ctcc.no")
set(CTEST_DROP_LOCATION      "/CDash/submit.php?project=XCFun")
set(CTEST_DROP_SITE_CDASH    TRUE)
