# Compile time options:
# -DNDEBUG Turn off run time checks in production calculations to gain speed
#NOTE: Using -fast gives wrong output from pbex, disappears at -O2
#level (without ipo) for icpc 10.1.017

# C++ compiler and flags
CXX=icpc
# Turn of messages that hide real errors
CXXFLAGS= -Wall -g -fPIC -O2  -fno-rtti -fno-exceptions -wd981 -wd279 -wd383 -vec-report0 -wd1572 -wd177

include Makefile.common
