# Compile time options:
# -DNDEBUG Turn off run time checks in production calculations to gain speed
# To compile without -lstdc++ needed use (g++) -fno-rtti -fno-exceptions
# -fno-threadsafe-statics. Note the last option.

# C compiler and flags
CC=gcc
CFLAGS=-g -Wall -O2 -DFTN_NO_UNDERSCORE

# C++ compiler and flags
CXX=g++
CXXFLAGS=$(CFLAGS) -fno-rtti -fno-exceptions

# Fortran compiler and flags (used for fortran/example.f90)
FC=xlf90
FFLAGS=-qmoddir=fortran -O3

include Makefile.common
